$GROUP "initialize"  when=4
dummy:	0
BitDummy:	0
OverRideSVSched_F:	OFF
OverRideB25Bld_F:	OFF
EIU_LoPwrStabTst_1:	OFF
EIU_LoPwrStabTst_2:	OFF
EIU_LoPwrStabTst_3:	OFF
ISO5_L227Cmd:	concat ("" "NUL")
ISO5Row:	0
ISO5Col:	0
ISO5ACode:	concat ("" "NUL")
ISO5ACode3:	concat ("" "NUL")
ISO5_356NUL_F:	ON
ISO5_356STX1_F:	OFF
ISO5_356STX_F:	OFF
ISO5_356ETX_F:	OFF
ISO5_356EOT_F:	OFF
ISO5_356FCls_F:	OFF
ISO5_356FOrg_F:	OFF
ISO5_356FStat_F:	OFF
ISO5_356FCSMR_F:	OFF
ISO5_356CFCls_F:	OFF
ISO5_356FMsg_N:	0
ISO5_356BWC_N:	0
ISO5_356BWCMx:	127
ISO5_356ATA0:	concat ("" "NUL")
ISO5_356ATA1:	concat ("" "NUL")
ISO5_356ATA2:	concat ("" "NUL")
ISO5_356ATA3:	concat ("" "NUL")
ISO5_356ATA4:	concat ("" "NUL")
ISO5_356ATA5:	concat ("" "NUL")
ISO5_356ATA6:	concat ("" "NUL")
ISO5_356ATA7:	concat ("" "NUL")
ISO5_356WD0:	concat ("" "NUL")
ISO5_356WD1:	concat ("" "NUL")
ISO5_356WD2:	concat ("" "NUL")
ISO5_356WD3:	concat ("" "NUL")
ISO5_356WD4:	concat ("" "NUL")
ISO5_356WD5:	concat ("" "NUL")
ISO5_356WD6:	concat ("" "NUL")
ISO5_356WD7:	concat ("" "NUL")
ISO5_WordCnt:	0
ISO5_BlokCnt:	0
LoopCount:	0
CtrlLoopTxt:	concat ("" "No Data")
CtrlLoopName:	concat ("" "INVALID")
EECACTypeTxt:	concat ("" "UNK")
EECEngRatTxt:	concat ("" "UNK")
MaxFuelUsed:	32000.0
PointTmr_F:	OFF
PointTmr:Sec	0.0
PointName:	concat ("", "EVENT")
OpTimer:	0.0
OpTimer_F:	OFF
PAIRs:		0.0
LPStabilityTest_RB:	0
ScanStoreInProgress:	OFF
NFHz:Hz	0.0
N1Hz:Hz	0.0
N2Hz:Hz	0.0
NFI:RPM	0.0
N1I:RPM	0.0
N2I:RPM	0.0
NFPctS:%	0.0
N1PctS:%	0.0
N2PctS:%	0.0
WfS:PPH	0.0
GenHz:Hz	0.0
Gen_Voltage:VAC	0.0
Gen_Current:mA	0.0
Ignition_A:AAC	0
Ignition_B:AAC	0
PCellFPSIG:PSIG	0.0
PCellRPSIG:PSIG	0.0
OATDegC:DegC	0.0
UnderCowlT1:DegC	0.0
BearScav:PSIG	0.0
QECMOP:PSID	0.0
QECFuelPress:PSIG	0.0
Bignumber:	999999
WeightFac:	0.85
EngineRunning:	OFF
EngineNotRunning:	ON
RunMode:	OFF
NotRunMode:	ON
EmergIdle_F:	OFF
IgnSystem:	concat ("" "IGN:")
EngTypeSTR:	concat ("" "UNK")
N1RnDnAtStop:RPM	0
N2RnDnAtStop:RPM	0
EGTAtStop:DegC	0
FuelCutOff_O:	ON
EngineOLimits_O:	OFF
NoLightoffMsg:	OFF
StartPeakEGT:DegC	0.0
StartPeakWf:PPH	0.0
FuelOnToIdle:secs	0.0
StrtOnToIdleTmr:secs	0.0
MotorTm:Sec	0.0
MotorSysTime:Sec	0.0
StableN1_F:	OFF
StableN2_F:	OFF
StableEGT_F:	OFF
StableEng_F:	OFF
#C *** Run-In Parameters ***
#C *** Alse see initsaveparams.cal ***
StageTmr_F:     OFF
StageTmr:Sec	0.0
StageTmrLim:Sec	0.0
ElapsedTmTmr:   0.0
Accel_F:	OFF
Decel_F:	OFF
RunInPause_F:   OFF
RunInTLA:Deg    0.0
TLA_Prev:Deg	0.0
TLA_Rate:Deg/Sec	0.0
TLAStartMn:Deg	0.0
TLAStartMx:Deg	0.0
TLATarg_F:	OFF
TLAAccel_F:	OFF
TLADecel_F:	OFF
TLAAccelMn:Deg	0.0
TLAAccelMx:Deg	0.0
TLADecelMn:Deg	0.0
TLADecelMx:Deg	0.0
#C * TLA_Targ is used for AutoThrottle Break-in Runs.
TLA_Targ:Deg	0.0
TLA_TargMn:Deg	0.0
TLA_TargMx:Deg	0.0
TLAAccelTarg:Deg	0.0
TLADecelTarg:Deg	0.0
N1C2R:RPM	0.0
N1C2R_Prev:RPM	0.0
N1C2_Rate:RPM/Sec	0.0
N1C2StartMn:RPM	0.0
N1C2StartMx:RPM	0.0
N1C2Targ_F:	OFF
N1C2Accel_F:	OFF
N1C2Decel_F:	OFF
N1C2AccelMn:RPM	0.0
N1C2AccelMx:RPM	0.0
N1C2DecelMn:RPM	0.0
N1C2DecelMx:RPM	0.0
N1C2_Targ:RPM	0.0
N1C2_TargMn:RPM	0.0
N1C2_TargMx:RPM	0.0
N1C2AccelTarg:RPM	0.0
N1C2DecelTarg:RPM	0.0
OverRideLPCBld:	OFF
N1AccelStop:RPM	0.0
N1DecelStop:RPM	0.0
GotoAI_F:       OFF
GotoGI_F:       OFF
GotoHold_F:     OFF
N1_ADBar_F:     OFF
N1_ADStart:RPM	0.0
N1_ADRat:RPM/Sec	0.0
ArmRunInHPC_TB:	OFF
ArmBrkInHPT_TB:	OFF
#C *** Break-In Parameters ***
BrkInPause_F:   OFF
#C ************************
#C Accel/Decel state for plotting vibs.
ADState:	1.0
#C Initialization for the Vib Peaks display
VibSmoothFact:	0.50
VibFBBPk:IPS	0.0
VibFBBPkN1:RPM	0.0
VibFBBPkN2:RPM	0.0
VibFN1Pk:IPS	0.0
VibFN1PkN1:RPM	0.0
VibFN1PkN2:RPM	0.0
VibFN2Pk:IPS	0.0
VibFN2PkN1:RPM	0.0
VibFN2PkN2:RPM	0.0
VibRBBPk:IPS	0.0
VibRBBPkN1:RPM	0.0
VibRBBPkN2:RPM	0.0
VibRN1Pk:IPS	0.0
VibRN1PkN1:RPM	0.0
VibRN1PkN2:RPM	0.0
VibRN2Pk:IPS	0.0
VibRN2PkN1:RPM	0.0
VibRN2PkN2:RPM	0.0
VibPeakDate:	concat ("" "No Data")
VibPeakTime:	concat ("" "No Data")
#C Initialize Vibration Signals...
VibFBB:IPS	0.0
VibF2BB:IPS	0.0
VibRBB:IPS	0.0
VibFN1:IPS	0.0
VibFN2:IPS	0.0
VibN2Frq:Hz	0.0
VibFAmp:IPS	0.0
VibN1Frq:Hz	0.0
VibFPhs:Deg	0.0
VibN1RPM:RPM	0.0
VibN2RPM:RPM	0.0
VibRN1:IPS	0.0
VibRN2:IPS	0.0
VibRAmp:IPS	0.0
VibRPhs:Deg	0.0
#C EGT overtemp timers...
EGTRunTrigTmr_F:	OFF
EGTRunTrigTmr:Sec	0.0
EGTRunMxTmr_F:		OFF
EGTRunMxTmr:Sec		0.0
EGTRunPk:DegC		0.0
EGTStrtTrigTmr_F:	OFF
EGTStrtTrigTmr:Sec	0.0
EGTStrtMxTmr_F:		OFF
EGTStrtMxTmr:Sec	0.0
EGTStrtPk:DegC		0.0
#C --- Under Cowl Temp Disable Flags -------
TNACSFSL_F:		OFF
TNACSFGR_F:		OFF
TNACSMPL_F:		OFF
TNACSMDR_F:		OFF
TNACSMVL_F:		OFF
TNACSMJR_F:		OFF
TNACSAPL_F:		OFF
TNACSADR_F:		OFF
TNACSAVL_F:		OFF
TNACSAJR_F:		OFF
TNACSFWD_F:		OFF
TNACSAFT_F:		OFF
$END-GROUP
