$GROUP "initsaveparams"  when=0
#C Emissions Data...
TotalCO:Lbs	0.0
TotalNOx:Lbs	0.0
TotalPM:Lbs	0.0
TotalSO2:Lbs	0.0
TotalVOC:Lbs	0.0
TotalTHC:Lbs	0.0
SHEA_ID:	concat ("" "No Data")
#C __________________________
TotalTestTime:Sec	0.0
AccelTm30:Sec		0.0
AccelTm90:Sec		0.0
DecelTm:Sec		0.0
#C __________________________
PeakEGT:DegC	0.0
FnAMax:Lbs	0.0
FnAMin:Lbs	0.0
FnBMax:Lbs	0.0
FnBMin:Lbs	0.0
FnCMax:Lbs	0.0
FnCMin:Lbs	0.0
FnDMax:Lbs	0.0
FnDMin:Lbs	0.0
#C __________________________
StrARVibPeaks_F:	OFF
StrVibPeaks_F:		OFF
StrVibFBBPk:IPS		0.0
StrVibFBBPkNF:IPS	0.0
StrVibFBBPkN1:RPM	0.0
StrVibFBBPkN2:RPM	0.0
StrVibFN1Pk:IPS		0.0
StrVibFN1PkNF:IPS	0.0
StrVibFN1PkN1:RPM	0.0
StrVibFN1PkN2:RPM	0.0
StrVibFN2Pk:IPS		0.0
StrVibFN2PkNF:IPS	0.0
StrVibFN2PkN1:RPM	0.0
StrVibFN2PkN2:RPM	0.0
StrVibRBBPk:IPS		0.0
StrVibRBBPkNF:IPS	0.0
StrVibRBBPkN1:RPM	0.0
StrVibRBBPkN2:RPM	0.0
StrVibRN1Pk:IPS		0.0
StrVibRN1PkNF:IPS	0.0
StrVibRN1PkN1:RPM	0.0
StrVibRN1PkN2:RPM	0.0
StrVibRN2Pk:IPS		0.0
StrVibRN2PkNF:IPS	0.0
StrVibRN2PkN1:RPM	0.0
StrVibRN2PkN2:RPM	0.0
StrVibPeakDate:	concat ("" "No Data")
StrVibPeakTime:	concat ("" "No Data")
#C __________________________
StrARVibFBBPk:IPS	0.0
StrARVibFBBPkNF:IPS	0.0
StrARVibFBBPkN1:RPM	0.0
StrARVibFBBPkN2:RPM	0.0
StrARVibFN1Pk:IPS	0.0
StrARVibFN1PkNF:IPS	0.0
StrARVibFN1PkN1:RPM	0.0
StrARVibFN1PkN2:RPM	0.0
StrARVibFN2Pk:IPS	0.0
StrARVibFN2PkNF:IPS	0.0
StrARVibFN2PkN1:RPM	0.0
StrARVibFN2PkN2:RPM	0.0
StrARVibRBBPk:IPS	0.0
StrARVibRBBPkNF:IPS	0.0
StrARVibRBBPkN1:RPM	0.0
StrARVibRBBPkN2:RPM	0.0
StrARVibRN1Pk:IPS	0.0
StrARVibRN1PkNF:IPS	0.0
StrARVibRN1PkN1:RPM	0.0
StrARVibRN1PkN2:RPM	0.0
StrARVibRN2Pk:IPS	0.0
StrARVibRN2PkNF:IPS	0.0
StrARVibRN2PkN1:RPM	0.0
StrARVibRN2PkN2:RPM	0.0
StrARVibPeakDate:	concat ("" "No Data")
StrARVibPeakTime:	concat ("" "No Data")
#C __________________________
FuelUsedInTest:Gal	0.0
TotalFuelUsed:Gal	0.0
TotalFuelUsedV:Gal	0.0
#C __________________________
#C Start Stop Data.....
StoreStartData:	0
StoreStartPrev:	0
StoreStopData:	0
StoreStopPrev:	0
StrStartData0:	concat (" " "")
StrStartData1:	concat (" " "")
StrStartData2:	concat (" " "")
StrStartData3:	concat (" " "")
StrStartData4:	concat (" " "")
StrStartData5:	concat (" " "")
StrStartData6:	concat (" " "")
StrStartData7:	concat (" " "")
StrStartData8:	concat (" " "")
StrStartData9:	concat (" " "")
StrStartData10:	concat (" " "")
StrStartData11:	concat (" " "")
StrStartData12:	concat (" " "")
StrStartData13:	concat (" " "")
StrStartData14:	concat (" " "")
StrStartData15:	concat (" " "")
StrStartData16:	concat (" " "")
StrStartData17:	concat (" " "")
StrStartData18:	concat (" " "")
StrStartData19:	concat (" " "")
StrStartData20:	concat (" " "")
StrStartData21:	concat (" " "")
StrStartData22:	concat (" " "")
StrStartData23:	concat (" " "")
StrStartData24:	concat (" " "")
StrStartData25:	concat (" " "")
StrStopData0:	concat (" " "")
StrStopData1:	concat (" " "")
StrStopData2:	concat (" " "")
StrStopData3:	concat (" " "")
StrStopData4:	concat (" " "")
StrStopData5:	concat (" " "")
StrStopData6:	concat (" " "")
StrStopData7:	concat (" " "")
StrStopData8:	concat (" " "")
StrStopData9:	concat (" " "")
StrStopData10:	concat (" " "")
StrStopData11:	concat (" " "")
StrStopData12:	concat (" " "")
StrStopData13:	concat (" " "")
StrStopData14:	concat (" " "")
StrStopData15:	concat (" " "")
StrStopData16:	concat (" " "")
StrStopData17:	concat (" " "")
StrStopData18:	concat (" " "")
StrStopData19:	concat (" " "")
StrStopData20:	concat (" " "")
StrStopData21:	concat (" " "")
StrStopData22:	concat (" " "")
StrStopData23:	concat (" " "")
StrStopData24:	concat (" " "")
StrStopData25:	concat (" " "")
#C ___________________________
FanWeight1:	concat("" "NONE")
FanWeight2:	concat("" "NONE")
FanWeight3:	concat("" "NONE")
FanWeight4:	concat("" "NONE")
FanWeight5:	concat("" "NONE")
FanWeight6:	concat("" "NONE")
FanWeight7:	concat("" "NONE")
FanWeight8:	concat("" "NONE")
FanWeight9:	concat("" "NONE")
FanWeight10:	concat("" "NONE")
FanWeightLoc1:	0
FanWeightLoc2:	0
FanWeightLoc3:	0
FanWeightLoc4:	0
FanWeightLoc5:	0
FanWeightLoc6:	0
FanWeightLoc7:	0
FanWeightLoc8:	0
FanWeightLoc9:	0
FanWeightLoc10:	0
TurbineWeightsUsed:	concat("" "0")
TurbineWeightsInst:	concat("" "0")
TurbineWeightsLoc:	concat("" "0")
#C __________________________
#C *** Run-In Parameters ***
RunInStage:     0
RunInStage1:    0
RunInStageTxt:  concat ("" "NO Data")
RunInState:     3
RunInStep:	0
RunInNibble:	0
#C *** Break-In Parameters ***
BrkInStage:     0
BrkInStageTxt:  concat ("" "NO Data")
BrkInState:     3
BrkInStep:	0
BrkInNibble:	0
#C *** MOP Test Parameters ***
MOPTstStage:	0
MOPTstStageTxt:	concat ("" "NO Data")
MOPTstPause_F:	OFF
MOPTstState:	0
#C ** Acceptance Auto-Throttle parameters ***
AcceptStep:	0
FNTR2Targ:Lbf	0.0
AcceptEventDur:	0.0
AcceptTLA:Deg	0.0
AcceptN1C2R:RPM	0.0
#C __________________________
N1CLASS:	0
#C __________________________
InstPOilCLASS:	0
InstPOilClass_RB:	50
InstPOilDiam:In	(InstPOilClass_RB / 1000)
POilTrim:In	0.0
POilTrimN:In	0.0
POilTrimP:In	0.0
POilTrimM:In	0.0
POilTrimClass:	0
POilTrimDiam:In	0.0
POilTrimDiamChg:In	0.0
POilTemp:DegC	0.0
POilN1:%	0.0
POilN2:%	0.0
POilCor:PSIG	0.0
POilMxLim:PSIG	0.0
POilMnLim:PSIG	0.0
POilNomLim:PSIG	0.0
POilNomRng:PSIG	0.0
POilDiff:PSIG	0.0
POilDiffSign:	0
#C __________________________
#C *** L253 Shutdown Timer params.
L253_SDTmr_F:	OFF
L253_SDTmr:sec	0.0
L253_SDTime:Min	180
EIU_L253B28:	ON
L253_SDTClose:	systime
#C __________________________
$END-GROUP
