$MSGGROUP "EEC Messages 36x CHB" 
$MSGBIT B2_360B11
0 msg="B360B11 - BAT Sensor OK"  color=Black 
1 msg="B360B11 - BAT Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B12
0 msg="B360B12 - FMU Overspeed Self Test OK"  color=Black 
1 msg="B360B12 - FMU Overspeed Self Test FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B15
0 msg="B360B15 - Starter Air Valve Opened OK"  color=Black 
1 msg="B360B15 - Starter Air Valve FAILED OPEN"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B16
0 msg="B360B16 - Starter Air Valve Closed OK"  color=Black 
1 msg="B360B16 - Starter Air Valve FAILED CLOSED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B17
0 msg="B360B17 - Buffer Air Valve Wrap Around OK"  color=Black 
1 msg="B360B17 - Buffer Air Valve Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B18
0 msg="B360B18 - Damper Oil Valve Wrap Around OK"  color=Black 
1 msg="B360B18 - Damper Oil Valve Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B20
0 msg="B360B20 - Aircraft 28 VDC Loss - Local OK"  color=Black 
1 msg="B360B20 - Aircraft 28 VDC Loss - Local"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B21
0 msg="B360B21 - Starter Speed Crosscheck OK"  color=Black 
1 msg="B360B21 - Starter Speed Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B22
0 msg="B360B22 - Mass Flow Meter OK"  color=Black 
1 msg="B360B22 - Mass Flow Meter FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B23
0 msg="B360B23 - Starter Clutch Mechanical OK"  color=Black 
1 msg="B360B23 - Starter Clutch Mechanical FAILURE"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B24
0 msg="B360B24 - SVA LVDT Feedback OK"  color=Black 
1 msg="B360B24 - SVA LVDT Feedback FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B25
0 msg="B360B25 - BAV Pressure Sensor Crosscheck OK"  color=Black 
1 msg="B360B25 - BAV Pressure Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B26
0 msg="B360B26 - TRA RVDT Feedback OK"  color=Black 
1 msg="B360B26 - TRA RVDT Feedback FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B27
0 msg="B360B27 - B25 NOT Out of Position"  color=Black 
1 msg="B360B27 - B25 Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B28
0 msg="B360B28 - SVA NOT Out of Position"  color=Black 
1 msg="B360B28 - SVA Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_360B29
0 msg="B360B29 - FMU NOT Out of Position"  color=Black 
1 msg="B360B29 - FMU Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B11
0 msg="B361B11 - Burner Pressure Sensor 1 Crosscheck OK"  color=Black 
1 msg="B361B11 - Burner Pressure Sensor 1 Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B12
0 msg="B361B12 - Burner Pressure Sensor 2 Crosscheck OK"  color=Black 
1 msg="B361B12 - Burner Pressure Sensor 2 Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B13
0 msg="B361B13 - CAI Temp Sensor OK"  color=Black 
1 msg="B361B13 - CAI Temp Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B14
0 msg="B361B14 - CAI Temp Sensor Crosscheck OK"  color=Black 
1 msg="B361B14 - CAI Temp Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B15
0 msg="B361B15 - Aux Oil Pump OK"  color=Black 
1 msg="B361B15 - Aux Oil Pump FAULT"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B16
0 msg="B361B16 - T5 Temperature Sensor Crosscheck OK"  color=Black 
1 msg="B361B16 - T5 Temperature Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B17
0 msg="B361B17 - TOIL Sensor Crosscheck OK"  color=Black 
1 msg="B361B17 - TOIL Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B18
0 msg="B361B18 - VORV Sensor Local Channel OK"  color=Black 
1 msg="B361B18 - VORV Sensor Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B19
0 msg="B361B19 - VORV Sensor Crosscheck OK"  color=Black 
1 msg="B361B19 - VORV Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B20
0 msg="B361B20 - T2 Temp Sensor Crosscheck OK"  color=Black 
1 msg="B361B20 - T2 Temp Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B21
0 msg="B361B21 - Lift TL Prox Switch Crosscheck OK"  color=Black 
1 msg="B361B21 - Lift TL Prox Switch Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B22
0 msg="B361B22 - Right TL Prox Switch Crosscheck OK"  color=Black 
1 msg="B361B22 - Right TL Prox Switch Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B23
0 msg="B361B23 - Left TLV NOT Failed OPEN"  color=Black 
1 msg="B361B23 - Left TLV Failed OPEN"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B24
0 msg="B361B24 - Right TLV NOT Failed OPEN"  color=Black 
1 msg="B361B24 - Right TLV Failed OPEN"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B25
0 msg="B361B25 - Auxiliary Oil Pressure Sensor OK"  color=Black 
1 msg="B361B25 - Auxiliary Oil Pressure Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B26
0 msg="B361B26 - Left Upper Actuator Lock NOT Failed Unlocked"  color=Black 
1 msg="B361B26 - Left Upper Actuator Lock FAILED Unlocked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B27
0 msg="B361B27 - Right Upper Actuator Lock NOT Failed Unlocked"  color=Black 
1 msg="B361B27 - Right Upper Actuator Lock Failed Unlocked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B28
0 msg="B361B28 - Left Lower Actuator Lock NOT Failed Unlocked"  color=Black 
1 msg="B361B28 - Left Lower Actuator Lock Failed Unlocked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_361B29
0 msg="B361B29 - Right Lower Actuator Lock NOT Failed Unlocked"  color=Black 
1 msg="B361B29 - Right Lower Actuator Lock Failed Unlocked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B11
0 msg="B362B11 - LPC Stator Vane LVDT Feedback OK"  color=Black 
1 msg="B362B11 - LPC Stator Vane LVDT Feedback FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B12
0 msg="B362B12 - LPC Stator Vane LVDT Crosscheck OK"  color=Black 
1 msg="B362B12 - LPC Stator Vane LVDT Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B13
0 msg="B362B13 - LPC Stator Vane Wrap Around OK"  color=Black 
1 msg="B362B13 - LPC Stator Vane Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B14
0 msg="B362B14 - LPC Stator Vane Null Shift OK"  color=Black 
1 msg="B362B14 - LPC Stator Vane Null Shift FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B15
0 msg="B362B15 - LPC Stator Vane NOT Out of Position"  color=Black 
1 msg="B362B15 - LPC Stator Vane Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B16
0 msg="B362B16 - HPC Bleed Sensor Local Channel OK"  color=Black 
1 msg="B362B16 - HPC Bleed Sensor Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B17
0 msg="B362B17 - HPC Bleed Sensor Crosscheck OK"  color=Black 
1 msg="B362B17 - HPC Bleed Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B19
0 msg="B362B19 - HPC Bleed Valve NOT Failed OPEN"  color=Black 
1 msg="B362B19 - HPC Bleed Valve Failed OPEN"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B20
0 msg="B362B20 - HPC Bleed Valve NOT Failed CLOSED"  color=Black 
1 msg="B362B20 - HPC Bleed Valve Failed CLOSED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B21
0 msg="B362B21 - PHMU CAN Bus OK"  color=Black 
1 msg="B362B21 - PHMU CAN Bus FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B22
0 msg="B362B22 - Fuel Temperature Crosscheck OK"  color=Black 
1 msg="B362B22 - Fuel Temperature Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B23
0 msg="B362B23 - PB 2 Local Channel OK"  color=Black 
1 msg="B362B23 - PB 2 Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B25
0 msg="B362B25 - Fuel Oil Cooler Wrap Around OK"  color=Black 
1 msg="B362B25 - Fuel Oil Cooler Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B26
0 msg="B362B26 - TR Wrap Around OK"  color=Black 
1 msg="B362B26 - TR Wrap Around FAULT"  color=Blue 
$END-MSGBIT
$MSGBIT B2_362B27
0 msg="B362B27 - Left TL NOT Failed Unlocked"  color=Black 
1 msg="B362B27 - Left TL Failed Unlocked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B28
0 msg="B362B28 - Right TL NOT Failed Unlocked"  color=Black 
1 msg="B362B28 - Right TL Failed Unlocked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_362B29
0 msg="B362B29 - Aux Oil Valve OK"  color=Black 
1 msg="B362B29 - Aux Oil Valve FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B11
0 msg="B363B11 - AOP Total FAULT OK"  color=Black 
1 msg="B363B11 - AOP Total FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B12
0 msg="B363B12 - BAV Total FAULT OK"  color=Black 
1 msg="B363B12 - BAV Total FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B13
0 msg="B363B13 - Reverser NOT Jammed"  color=Black 
1 msg="B363B13 - Reverser Jammed"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B15
0 msg="B363B15 - TAI CrossChannel OK"  color=Black 
1 msg="B363B15 - TAI CrossChannel FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B19
0 msg="B363B19 - PHMU N1 OK"  color=Black 
1 msg="B363B19 - PHMU N1 FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B20
0 msg="B363B20 - PHMU N2 OK"  color=Black 
1 msg="B363B20 - PHMU N2 FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B21
0 msg="B363B21 - PHMU NF OK"  color=Black 
1 msg="B363B21 - PHMU NF FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B22
0 msg="B363B22 - EEC Software Compatibility OK"  color=Black 
1 msg="B363B22 - EEC Software Compatibility FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B23
0 msg="B363B23 - Left Track Lock NOT Failed Locked"  color=Black 
1 msg="B363B23 - Left Track Lock Failed Locked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B24
0 msg="B363B24 - Right Track Lock NOT Failed Locked"  color=Black 
1 msg="B363B24 - Right Track Lock Failed Locked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B25
0 msg="B363B25 - Left Lower Actuator Lock NOT Failed Locked"  color=Black 
1 msg="B363B25 - Left Lower Actuator Lock Failed Locked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B26
0 msg="B363B26 - Left Upper Actuator Lock NOT Failed Locked"  color=Black 
1 msg="B363B26 - Left Upper Actuator Lock Failed Locked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B27
0 msg="B363B27 - Right Lower Actuator Lock NOT Failed Locked"  color=Black 
1 msg="B363B27 - Right Lower Actuator Lock Failed Locked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B28
0 msg="B363B28 - Right Upper Actuator Lock NOT Failed Locked"  color=Black 
1 msg="B363B28 - Right Upper Actuator Lock Failed Locked"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_363B29
0 msg="B363B29 - Engine T2 CrossChannel OK"  color=Black 
1 msg="B363B29 - Engine T2 CrossChannel FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B11
0 msg="B366B11 - EEC Internal No Dispatch OK"  color=Black 
1 msg="B366B11 - EEC Internal No Dispatch FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B12
0 msg="B366B12 - EEC Internal Short Term Dispatch OK"  color=Black 
1 msg="B366B12 - EEC Internal Short Term Dispatch FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B13
0 msg="B366B13 - EEC Internal Long Term Dispatch OK"  color=Black 
1 msg="B366B13 - EEC Internal Long Term Dispatch FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B14
0 msg="B366B14 - EEC Internal FAULT OK"  color=Black 
1 msg="B366B14 - EEC Internal FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B15
0 msg="B366B15 - ODM FE Short Term NOT Exceeded"  color=Black 
1 msg="B366B15 - ODM FE Short Term Exceeded"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B16
0 msg="B366B16 - ODM FE Long Term NOT Exceeded"  color=Black 
1 msg="B366B16 - ODM FE Long Term Exceeded"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B17
0 msg="B366B17 - ODM NFE Short Term NOT Exceeded"  color=Black 
1 msg="B366B17 - ODM NFE Short Term Exceeded"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B18
0 msg="B366B18 - ODM NFE Long Term NOT Exceeded"  color=Black 
1 msg="B366B18 - ODM NFE Long Term Exceeded"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B19
0 msg="B366B19 - BASOV Wrap Around OK"  color=Black 
1 msg="B366B19 - BASOV Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B20
0 msg="B366B20 - BASOV NOT Failed OPEN"  color=Black 
1 msg="B366B20 - BASOV Failed OPEN"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B21
0 msg="B366B21 - Buffer System OK"  color=Black 
1 msg="B366B21 - Buffer System FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B22
0 msg="B366B22 - BACVFO NOT Failed OPEN"  color=Black 
1 msg="B366B22 - BACVFO Failed OPEN"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B23
0 msg="B366B23 - BACVFC NOT Failed CLOSED"  color=Black 
1 msg="B366B23 - BACVFC Failed CLOSED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_366B25
0 msg="B366B25 - CAI2 Pressure Sensor OK"  color=Black 
1 msg="B366B25 - CAI2 Pressure Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$END-MSGGROUP
