$MSGGROUP "EEC Messages 35x CHB" 
$MSGBIT B2_350B11
0 msg="B350B11 - N1 Local Sensor Channel OK"  color=Black 
1 msg="B350B11 - N1 Local Sensor Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B12
0 msg="B350B12 - N2 Local Sensor Channel OK"  color=Black 
1 msg="B350B12 - N2 Local Sensor Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B13
0 msg="B350B13 - T2 Temperature Sensor Local Channel OK"  color=Black 
1 msg="B350B13 - T2 Temperature Sensor Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B14
0 msg="B350B14 - Fuel Meter Valve LVDT Local Channel OK"  color=Black 
1 msg="B350B14 - Fuel Meter Valve LVDT Local Channel FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B15
0 msg="B350B15 - 2.5 Bleed LVDT Local Channel OK"  color=Black 
1 msg="B350B15 - 2.5 Bleed LVDT Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B16
0 msg="B350B16 - One TRA RVDT signal OK"  color=Black 
1 msg="B350B16 - One TRA RVDT signal FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B17
0 msg="B350B17 - Fan Speed Local Channel OK"  color=Black 
1 msg="B350B17 - Fan Speed Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B18
0 msg="B350B18 - Low Pressure Compressor Exit Total Press OK"  color=Black 
1 msg="B350B18 - Low Pressure Compressor Exit Total Press FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B19
0 msg="B350B19 - Low Pressure Compressor Exit Total Temp OK"  color=Black 
1 msg="B350B19 - Low Pressure Compressor Exit Total Temp FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B20
0 msg="B350B20 - T3 Thermocouple reference Cold Junction Compensation OK"  color=Black 
1 msg="B350B20 - T3 Thermocouple reference Cold Junction Compensation FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B21
0 msg="B350B21 - PB 1 Local Channel OK"  color=Black 
1 msg="B350B21 - PB 1 Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B22
0 msg="B350B22 - Fuel Meter Valve TM Wrap Around OK"  color=Black 
1 msg="B350B22 - Fuel Meter Valve TM Wrap Around FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B23
0 msg="B350B23 - Stator Vane Act TM Wrap Around OK"  color=Black 
1 msg="B350B23 - Stator Vane Act TM Wrap Around FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B24
0 msg="B350B24 - 2.5 Bleed Torque Motor Wrap Around OK"  color=Black 
1 msg="B350B24 - 2.5 Bleed Torque Motor Wrap Around FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B25
0 msg="B350B25 - T3 Temperature Sensor Local Channel OK"  color=Black 
1 msg="B350B25 - T3 Temperature Sensor Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B26
0 msg="B350B26 - T5 Temperature Sensor Local Channel OK"  color=Black 
1 msg="B350B26 - T5 Temperature Sensor Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B27
0 msg="B350B27 - Starter Speed Sensor Local Channel OK"  color=Black 
1 msg="B350B27 - Starter Speed Sensor Local Channel FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B28
0 msg="B350B28 - Igniter 1 relay circuit OK"  color=Black 
1 msg="B350B28 - Igniter 1 relay circuit FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_350B29
0 msg="B350B29 - Igniter 2 relay circuit OK"  color=Black 
1 msg="B350B29 - Igniter 2 relay circuit FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B11
0 msg="B351B11 - PMA circuit OK"  color=Black 
1 msg="B351B11 - PMA circuit FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B12
0 msg="B351B12 - P2 Pneumatic Line OK"  color=Black 
1 msg="B351B12 - P2 Pneumatic Line FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B13
0 msg="B351B13 - Pambient Probe OK"  color=Black 
1 msg="B351B13 - Pambient Probe FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B14
0 msg="B351B14 - Fan Speed Sensor Crosscheck OK"  color=Black 
1 msg="B351B14 - Fan Speed Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B15
0 msg="B351B15 - N1 Speed Sensor Crosscheck OK"  color=Black 
1 msg="B351B15 - N1 Speed Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B16
0 msg="B351B16 - N2 Speed Sensor Crosscheck OK"  color=Black 
1 msg="B351B16 - N2 Speed Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B18
0 msg="B351B18 - Engine Run/Stop Switch Discrete OK"  color=Black 
1 msg="B351B18 - Engine Run/Stop Switch Discrete FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B19
0 msg="B351B19 - Pb Line OK"  color=Black 
1 msg="B351B19 - Pb Line Leak or Clog"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B20
0 msg="B351B20 - ENG Run Pat OK"  color=Black 
1 msg="B351B20 - ENG Run Pat FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B21
0 msg="B351B21 - TF Temperature Sensor OK"  color=Black 
1 msg="B351B21 - TF Temperature Sensor FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B22
0 msg="B351B22 - TOIL Temperature Sensor OK"  color=Black 
1 msg="B351B22 - TOIL Temperature Sensor FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B23
0 msg="B351B23 - WF LVDT Crosscheck OK"  color=Black 
1 msg="B351B23 - WF LVDT Crosscheck FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B24
0 msg="B351B24 - SVA LVDT Crosscheck OK"  color=Black 
1 msg="B351B24 - SVA LVDT Crosscheck FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B26
0 msg="B351B26 - FOC BV OK"  color=Black 
1 msg="B351B26 - FOC BV Out of Position"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B27
0 msg="B351B27 - ENG Run Xchannel OK"  color=Black 
1 msg="B351B27 - ENG Run Xchannel FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B28
0 msg="B351B28 - ENG OFF Xchannel OK"  color=Black 
1 msg="B351B28 - ENG OFF Xchannel FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_351B29
0 msg="B351B29 - 2.5 Bleed LVDT Crosscheck OK"  color=Black 
1 msg="B351B29 - 2.5 Bleed LVDT Crosscheck FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B11
0 msg="B352B11 - TRA Signal Crosscheck OK"  color=Black 
1 msg="B352B11 - TRA Signal Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B12
0 msg="B352B12 - ARINC Output Bus 1 Wrap Around OK"  color=Black 
1 msg="B352B12 - ARINC Output Bus 1 Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B13
0 msg="B352B13 - ARINC Output Bus 2 Wrap Around OK"  color=Black 
1 msg="B352B13 - ARINC Output Bus 2 Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B14
0 msg="B352B14 - Oil Debris OK"  color=Black 
1 msg="B352B14 - Oil Debris Above Limit"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B15
0 msg="B352B15 - Oil Filter NOT ByPass"  color=Black 
1 msg="B352B15 - Oil Filter ByPass"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B16
0 msg="B352B16 - Fuel Filter NOT ByPass"  color=Black 
1 msg="B352B16 - Fuel Filter ByPass"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B17
0 msg="B352B17 - Fuel Divider Valve Wrap Around OK"  color=Black 
1 msg="B352B17 - Fuel Divider Valve Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B18
0 msg="B352B18 - Overspeed Solenoid Wrap Around OK"  color=Black 
1 msg="B352B18 - Overspeed Solenoid Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B20
0 msg="B352B20 - Oil Debris Monitor OK"  color=Black 
1 msg="B352B20 - Oil Debris Monitor FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B21
0 msg="B352B21 - Starter Air Valve Solenoid Circuit OK"  color=Black 
1 msg="B352B21 - Starter Air Valve Solenoid Circuit FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B22
0 msg="B352B22 - Oil Filter NOT Impending Bypass"  color=Black 
1 msg="B352B22 - Oil Filter Impending Bypass"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B23
0 msg="B352B23 - Fuel Filter NOT Impending Bypass"  color=Black 
1 msg="B352B23 - Fuel Filter Impending Bypass"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B24
0 msg="B352B24 - Oil Filter Delta Pressure Sensor OK"  color=Black 
1 msg="B352B24 - Oil Filter Delta Pressure Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B25
0 msg="B352B25 - Oil Filter Delta Pressure Crosscheck OK"  color=Black 
1 msg="B352B25 - Oil Filter Delta Pressure Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B26
0 msg="B352B26 - Fuel Filter Delta Pressure Sensor OK"  color=Black 
1 msg="B352B26 - Fuel Filter Delta Pressure Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B27
0 msg="B352B27 - Fuel Filter Delta Pressure Crosscheck OK"  color=Black 
1 msg="B352B27 - Fuel Filter Delta Pressure Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B28
0 msg="B352B28 - Oil Pressure Sensor OK"  color=Black 
1 msg="B352B28 - Oil Pressure Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_352B29
0 msg="B352B29 - Oil Pressure Sensor Crosscheck OK"  color=Black 
1 msg="B352B29 - Oil Pressure Sensor Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B11
0 msg="B353B11 - CAI Wrap Around OK Solenoid 1"  color=Black 
1 msg="B353B11 - CAI Wrap Around FAULT Solenoid 1"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B12
0 msg="B353B12 - ICV Valve Closed OK"  color=Black 
1 msg="B353B12 - ICV Valve FAILED Closed"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B13
0 msg="B353B13 - REVL LVDT Feedback OK"  color=Black 
1 msg="B353B13 - REVL LVDT Feedback FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B14
0 msg="B353B14 - REVL LVDT Crosscheck OK"  color=Black 
1 msg="B353B14 - REVL LVDT Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B15
0 msg="B353B15 - REVR LVDT Feedback OK"  color=Black 
1 msg="B353B15 - REVR LVDT Feedback FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B16
0 msg="B353B16 - REVR LVDT Crosscheck OK"  color=Black 
1 msg="B353B16 - REVR LVDT Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B17
0 msg="B353B17 - ICV Proximity Pressure Switch OK"  color=Black 
1 msg="B353B17 - ICV Proximity Pressure Switch FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B18
0 msg="B353B18 - ICV Proximity Pressure Switch Crosscheck OK"  color=Black 
1 msg="B353B18 - ICV Proximity Pressure Switch Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B19
0 msg="B353B19 - ICV Valve Open OK"  color=Black 
1 msg="B353B19 - ICV Valve FAILED Open"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B20
0 msg="B353B20 - ICV Inhibit Proximity Switch OK"  color=Black 
1 msg="B353B20 - ICV Inhibit Proximity Switch FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B21
0 msg="B353B21 - ICV Inhibit Proximity Switch Crosscheck OK"  color=Black 
1 msg="B353B21 - ICV Inhibit Proximity Switch Crosscheck FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B22
0 msg="B353B22 - Hydraulic Pump Disconnect Wrap Around OK"  color=Black 
1 msg="B353B22 - Hydraulic Pump Disconnect Wrap Around FAULT"  color=Blue  
$END-MSGBIT
$MSGBIT B2_353B23
0 msg="B353B23 - VORV Wrap Around OK"  color=Black 
1 msg="B353B23 - VORV Wrap Around FAILURE"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B24
0 msg="B353B24 - VORV Null Shaft OK"  color=Black 
1 msg="B353B24 - VORV Null Shaft FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B25
0 msg="B353B25 - FMV Null Shaft OK"  color=Black 
1 msg="B353B25 - FMV Null Shaft FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B26
0 msg="B353B26 - SVA Null Shaft OK"  color=Black 
1 msg="B353B26 - SVA Null Shaft FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B27
0 msg="B353B27 - B25 Null Shaft OK"  color=Black 
1 msg="B353B27 - B25 Null Shaft FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B28
0 msg="B353B28 - DCV Wrap Around OK"  color=Black 
1 msg="B353B28 - DCV Wrap Around FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_353B29
0 msg="B353B29 - VORV NOT Out of Position"  color=Black 
1 msg="B353B29 - VORV Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B11
0 msg="B354B11 - EEC Overheat OK"  color=Black 
1 msg="B354B11 - EEC Overheat"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B12
0 msg="B354B12 - Both DMC Busses OK"  color=Black 
1 msg="B354B12 - Both DMC Busses FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B13
0 msg="B354B13 - Nacelle NOT Overheat"  color=Black 
1 msg="B354B13 - Nacelle Overheat"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B15
0 msg="B354B15 - Engine Lightoff while igniter 1 commanded"  color=Black 
1 msg="B354B15 - No Engine Lightoff while igniter 1 commanded"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B16
0 msg="B354B16 - Engine Lightoff while igniter 2 commanded"  color=Black 
1 msg="B354B16 - No Engine Lightoff while igniter 2 commanded"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B17
0 msg="B354B17 - ACC Torque Motor OK"  color=Black 
1 msg="B354B17 - ACC Torque Motor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B18
0 msg="B354B18 - ACC NOT Out of Position"  color=Black 
1 msg="B354B18 - ACC Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B19
0 msg="B354B19 - ACC Null Shift OK"  color=Black 
1 msg="B354B19 - ACC Null Shift FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B20
0 msg="B354B20 - ACC LVDT Feedback OK"  color=Black 
1 msg="B354B20 - ACC LVDT Feedback FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B21
0 msg="B354B21 - P2T2 Probe heater power or heater element OK"  color=Black 
1 msg="B354B21 - P2T2 Probe heater power or heater element FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B22
0 msg="B354B22 - Engine Position Discretes OK"  color=Black 
1 msg="B354B22 - Engine Position Discretes DISAGREE"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B23
0 msg="B354B23 - Receiver 1 OK"  color=Black 
1 msg="B354B23 - Receiver 1 FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B24
0 msg="B354B24 - Receiver 2 OK"  color=Black 
1 msg="B354B24 - Receiver 2 FAILED"  color=Blue  
$END-MSGBIT
$MSGBIT B2_354B25
0 msg="B354B25 - Engine Position Indication OK"  color=Black 
1 msg="B354B25 - Engine Position Indication FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B26
0 msg="B354B26 - PHMU Internal Fault OK"  color=Black 
1 msg="B354B26 - PHMU Internal Fault"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B27
0 msg="B354B27 - FDV NOT Out of Position"  color=Black 
1 msg="B354B27 - FDV Out of Position"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_354B28
0 msg="B354B28 - Pre-Cooler Exit Door Linear Actuator Motor OK"  color=Black 
1 msg="B354B28 - Pre-Cooler Exit Door Linear Actuator Motor FAILED"  color=Blue  
$END-MSGBIT
$MSGBIT B2_355B11
0 msg="B355B11 - Cowl Anti-Ice NOT Failed ON"  color=Black 
1 msg="B355B11 - Cowl Anti-Ice Failed ON"  color=Red  
$END-MSGBIT
$MSGBIT B2_355B12
0 msg="B355B12 - Cowl Anti-Ice NOT Failed ON"  color=Black 
1 msg="B355B12 - Cowl Anti-Ice NOT Failed ON"  color=Blue 
$END-MSGBIT
$MSGBIT B2_355B14
0 msg="B355B14 - CAI Miscompare OK"  color=Black 
1 msg="B355B14 - CAI Miscompare FAULT"  color=Blue  
$END-MSGBIT
$MSGBIT B2_355B15
0 msg="B355B15 - TR Left Lock Actuator Prox Switch OK"  color=Black 
1 msg="B355B15 - TR Left Lock Actuator Prox Switch FAILED"  color=BurntOrange  
$END-MSGBIT
$MSGBIT B2_355B16
0 msg="B355B16 - TR Right Lock Actuator Prox Switch OK"  color=Black 
1 msg="B355B16 - TR Right Lock Actuator Prox Switch FAILED"  color=BurntOrange  
$END-MSGBIT
$MSGBIT B2_355B17
0 msg="B355B17 - TR Left Lock Feedback Act Prox Switch OK"  color=Black 
1 msg="B355B17 - TR Left Lock Feedback Act Prox Switch FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B18
0 msg="B355B18 - TR Right Lock Feedback Act Prox Switch OK"  color=Black 
1 msg="B355B18 - TR Right Lock Feedback Act Prox Switch FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B19
0 msg="B355B19 - ICV Solenoid OK"  color=Black 
1 msg="B355B19 - ICV Solenoid FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B20
0 msg="B355B20 - ICV 28 VDC Power Supply OK"  color=Black 
1 msg="B355B20 - ICV 28 VDC Power Supply FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B21
0 msg="B355B21 - Uncommanded ICV 28 VDC Power Supply OK"  color=Black 
1 msg="B355B21 - Uncommanded ICV 28 VDC Power Supply"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B23
0 msg="B355B23 - DCV NOT Failed CLOSED"  color=Black 
1 msg="B355B23 - DCV FAILED CLOSED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B25
0 msg="B355B25 - N2 Vib Sensor OK"  color=Black 
1 msg="B355B25 - N2 Vib Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B26
0 msg="B355B26 - Left Sleeve Track Lock Proximity Switch OK"  color=Black 
1 msg="B355B26 - Left Sleeve Track Lock Proximity Switch FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B27
0 msg="B355B27 - Right Sleeve Track Lock Proximity Switch OK"  color=Black 
1 msg="B355B27 - Right Sleeve Track Lock Proximity Switch FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B28
0 msg="B355B28 - DCV NOT Failed CLOSED"  color=Black 
1 msg="B355B28 - DCV FAILED CLOSED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_355B29
0 msg="B355B29 - Oil Quantity Sensor OK"  color=Black 
1 msg="B355B29 - Oil Quantity Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B11
0 msg="B357B11 - PHMU OK"  color=Black 
1 msg="B357B11 - PHMU FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B12
0 msg="B357B12 - Duct Burst NOT Detected"  color=Black 
1 msg="B357B12 - Duct Burst Detected"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B13
0 msg="B357B13 - CAI Wrap Around NO Fault Solenoid 2"  color=Black 
1 msg="B357B13 - CAI Wrap Around FAULT Solenoid 2"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B14
0 msg="B357B14 - CAI PRSOV 1 NOT Failed Open or regulating high"  color=Black 
1 msg="B357B14 - CAI PRSOV 1 FAILED OPEN or regulating high"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B15
0 msg="B357B15 - CAI PRSOV 2 NOT Failed Open or regulating high"  color=Black 
1 msg="B357B15 - CAI PRSOV 2 FAILED OPEN or regulating high"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B16
0 msg="B357B16 - CAI Regulating Low Valve OK"  color=Black 
1 msg="B357B16 - CAI Regulating Low Valve"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B17
0 msg="B357B17 - Vibration 1 Sensor OK"  color=Black 
1 msg="B357B17 - Vibration 1 Sensor FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B18
0 msg="B357B18 - Vibration 2 Sensor OK"  color=Black 
1 msg="B357B18 - Vibration 2 Sensor FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B19
0 msg="B357B19 - ODM Sensor OK"  color=Black 
1 msg="B357B19 - ODM Sensor FAULT"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B20
0 msg="B357B20 - Steep Approach OK"  color=Black 
1 msg="B357B20 - Steep Approach Inoperative"  color=Blue  
$END-MSGBIT
$MSGBIT B2_357B21
0 msg="B357B21 - Flex Temp Function OK"  color=Black 
1 msg="B357B21 - Flex Temp Function FAILED"  color=Blue  
$END-MSGBIT
$MSGBIT B2_357B22
0 msg="B357B22 - BAV Pressure Sensor OK"  color=Black 
1 msg="B357B22 - BAV Pressure Sensor FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B23
0 msg="B357B23 - EEC Opposite Channel Control Processor OK"  color=Black 
1 msg="B357B23 - EEC Opposite Channel Control Processor FAILED"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B24
0 msg="B357B24 - EEC Channel OK/Capable to control"  color=Black 
1 msg="B357B24 - EEC Channel FAILED/NOT Capable to control"  color=Red  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B26
0 msg="B357B26 - TLA Excitation Circuitry OK"  color=Black 
1 msg="B357B26 - TLA Excitation Circuitry FAILED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B27
0 msg="B357B27 - DSU NO Failure Detected"  color=Black 
1 msg="B357B27 - DSU FAILURE DETECTED"  color=BurntOrange  MSGQ 
$END-MSGBIT
$MSGBIT B2_357B29
0 msg="B357B29 - EEC remote Channel OK/Capable to control"  color=Black 
1 msg="B357B29 - EEC remote Channel FAILED/NOT Capable to control"  color=Red  MSGQ 
$END-MSGBIT
$END-MSGGROUP
